ERROR:tornado.application: Uncaught exception GET / (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/', version='HTTP/1.1', remote_ip='::1', headers={'Host': 'localhost:8888', 'Connection': 'keep-alive', 'Upgrade-Insecure-Requests': '1', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'Dnt': '1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept-Language': 'en,es;q=0.9,ca;q=0.8', 'Cookie': 'cookie_ue=1; csrftoken=fIWxIocjADcqNZ1wrwmd5Jda9qvw2iPVdjdsURbbYmSqecZ9HyTsjmHxeVcEp2Jw; mp_26329f50afff012d48b9822b1da66b66_mixpanel=%7B%22distinct_id%22%3A%20%221618f0705b9478-01daa349961edb-32637401-1fa400-1618f0705ba678%22%2C%22%24initial_referrer%22%3A%20%22%24direct%22%2C%22%24initial_referring_domain%22%3A%20%22%24direct%22%7D; _xsrf=2|e1488547|698a7be1f69e283076cfb9258599c80e|1519975023; username-localhost-8888="2|1:0|10:1520412817|23:username-localhost-8888|44:ZGY3ZTIwMmVkZTVlNDk0MmI5Mzk3ODM1YWVkY2E2YjM=|4ddb8cb8f7b23f808d453a3c6f0a490d314efa05ec343de733617f64006d59b5"'}) (2018-03-10 19:57:52; web.py:1591)
Traceback (most recent call last):
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/web.py", line 1512, in _execute
    result = yield result
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
  File "/Users/Mat/anaconda/lib/python3.6/types.py", line 248, in wrapped
    coro = func(*args, **kwargs)
  File "/Users/Mat/github/tornado-app/src/app/models/home/handlers.py", line 11, in get
    self.render("home.html")
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/web.py", line 724, in render
    html = self.render_string(template_name, **kwargs)
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/web.py", line 862, in render_string
    t = loader.load(template_name)
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/template.py", line 427, in load
    self.templates[name] = self._create_template(name)
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/template.py", line 454, in _create_template
    with open(path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/Mat/github/tornado-app/src/app/models/home/home.html'
ERROR:tornado.access: 500 GET / (::1) 6.95ms (2018-03-10 19:57:52; web.py:2064)
WARNING:tornado.access: 404 GET /favicon.ico (::1) 0.53ms (2018-03-10 19:57:52; web.py:2064)
ERROR:tornado.application: Uncaught exception GET / (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/', version='HTTP/1.1', remote_ip='::1', headers={'Host': 'localhost:8888', 'Connection': 'keep-alive', 'Cache-Control': 'max-age=0', 'Upgrade-Insecure-Requests': '1', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'Dnt': '1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept-Language': 'en,es;q=0.9,ca;q=0.8', 'Cookie': 'cookie_ue=1; csrftoken=fIWxIocjADcqNZ1wrwmd5Jda9qvw2iPVdjdsURbbYmSqecZ9HyTsjmHxeVcEp2Jw; mp_26329f50afff012d48b9822b1da66b66_mixpanel=%7B%22distinct_id%22%3A%20%221618f0705b9478-01daa349961edb-32637401-1fa400-1618f0705ba678%22%2C%22%24initial_referrer%22%3A%20%22%24direct%22%2C%22%24initial_referring_domain%22%3A%20%22%24direct%22%7D; _xsrf=2|e1488547|698a7be1f69e283076cfb9258599c80e|1519975023; username-localhost-8888="2|1:0|10:1520412817|23:username-localhost-8888|44:ZGY3ZTIwMmVkZTVlNDk0MmI5Mzk3ODM1YWVkY2E2YjM=|4ddb8cb8f7b23f808d453a3c6f0a490d314efa05ec343de733617f64006d59b5"'}) (2018-03-10 19:59:26; web.py:1591)
Traceback (most recent call last):
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/web.py", line 1512, in _execute
    result = yield result
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
  File "/Users/Mat/anaconda/lib/python3.6/types.py", line 248, in wrapped
    coro = func(*args, **kwargs)
  File "/Users/Mat/github/tornado-app/src/app/models/home/handlers.py", line 11, in get
    self.render("home.html")
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/web.py", line 724, in render
    html = self.render_string(template_name, **kwargs)
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/web.py", line 862, in render_string
    t = loader.load(template_name)
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/template.py", line 427, in load
    self.templates[name] = self._create_template(name)
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/template.py", line 454, in _create_template
    with open(path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/Mat/github/tornado-app/src/app/models/home/home.html'
ERROR:tornado.access: 500 GET / (::1) 18.30ms (2018-03-10 19:59:26; web.py:2064)
ERROR:tornado.application: Uncaught exception GET / (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/', version='HTTP/1.1', remote_ip='::1', headers={'Host': 'localhost:8888', 'Connection': 'keep-alive', 'Cache-Control': 'max-age=0', 'Upgrade-Insecure-Requests': '1', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'Dnt': '1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept-Language': 'en,es;q=0.9,ca;q=0.8', 'Cookie': 'cookie_ue=1; csrftoken=fIWxIocjADcqNZ1wrwmd5Jda9qvw2iPVdjdsURbbYmSqecZ9HyTsjmHxeVcEp2Jw; mp_26329f50afff012d48b9822b1da66b66_mixpanel=%7B%22distinct_id%22%3A%20%221618f0705b9478-01daa349961edb-32637401-1fa400-1618f0705ba678%22%2C%22%24initial_referrer%22%3A%20%22%24direct%22%2C%22%24initial_referring_domain%22%3A%20%22%24direct%22%7D; _xsrf=2|e1488547|698a7be1f69e283076cfb9258599c80e|1519975023; username-localhost-8888="2|1:0|10:1520412817|23:username-localhost-8888|44:ZGY3ZTIwMmVkZTVlNDk0MmI5Mzk3ODM1YWVkY2E2YjM=|4ddb8cb8f7b23f808d453a3c6f0a490d314efa05ec343de733617f64006d59b5"'}) (2018-03-10 20:02:49; web.py:1591)
Traceback (most recent call last):
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/web.py", line 1512, in _execute
    result = yield result
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
  File "/Users/Mat/anaconda/lib/python3.6/types.py", line 248, in wrapped
    coro = func(*args, **kwargs)
  File "/Users/Mat/github/tornado-app/src/app/models/home/handlers.py", line 11, in get
    self.render(TEMPLATE_ROOT + "home.html")
NameError: name 'TEMPLATE_ROOT' is not defined
ERROR:tornado.access: 500 GET / (::1) 8.57ms (2018-03-10 20:02:49; web.py:2064)
ERROR:tornado.application: Uncaught exception GET / (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/', version='HTTP/1.1', remote_ip='::1', headers={'Host': 'localhost:8888', 'Connection': 'keep-alive', 'Cache-Control': 'max-age=0', 'Upgrade-Insecure-Requests': '1', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'Dnt': '1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept-Language': 'en,es;q=0.9,ca;q=0.8', 'Cookie': 'cookie_ue=1; csrftoken=fIWxIocjADcqNZ1wrwmd5Jda9qvw2iPVdjdsURbbYmSqecZ9HyTsjmHxeVcEp2Jw; mp_26329f50afff012d48b9822b1da66b66_mixpanel=%7B%22distinct_id%22%3A%20%221618f0705b9478-01daa349961edb-32637401-1fa400-1618f0705ba678%22%2C%22%24initial_referrer%22%3A%20%22%24direct%22%2C%22%24initial_referring_domain%22%3A%20%22%24direct%22%7D; _xsrf=2|e1488547|698a7be1f69e283076cfb9258599c80e|1519975023; username-localhost-8888="2|1:0|10:1520412817|23:username-localhost-8888|44:ZGY3ZTIwMmVkZTVlNDk0MmI5Mzk3ODM1YWVkY2E2YjM=|4ddb8cb8f7b23f808d453a3c6f0a490d314efa05ec343de733617f64006d59b5"'}) (2018-03-10 20:03:35; web.py:1591)
Traceback (most recent call last):
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/web.py", line 1512, in _execute
    result = yield result
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
  File "/Users/Mat/anaconda/lib/python3.6/types.py", line 248, in wrapped
    coro = func(*args, **kwargs)
  File "/Users/Mat/github/tornado-app/src/app/models/home/handlers.py", line 11, in get
    self.render( "/Users/Mat/github/tornado-app/src/app/home.html")
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/web.py", line 724, in render
    html = self.render_string(template_name, **kwargs)
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/web.py", line 862, in render_string
    t = loader.load(template_name)
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/template.py", line 427, in load
    self.templates[name] = self._create_template(name)
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/template.py", line 454, in _create_template
    with open(path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/Mat/github/tornado-app/src/app/home.html'
ERROR:tornado.access: 500 GET / (::1) 7.37ms (2018-03-10 20:03:35; web.py:2064)
ERROR:tornado.application: Uncaught exception GET / (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/', version='HTTP/1.1', remote_ip='::1', headers={'Host': 'localhost:8888', 'Connection': 'keep-alive', 'Cache-Control': 'max-age=0', 'Upgrade-Insecure-Requests': '1', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'Dnt': '1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept-Language': 'en,es;q=0.9,ca;q=0.8', 'Cookie': 'cookie_ue=1; csrftoken=fIWxIocjADcqNZ1wrwmd5Jda9qvw2iPVdjdsURbbYmSqecZ9HyTsjmHxeVcEp2Jw; mp_26329f50afff012d48b9822b1da66b66_mixpanel=%7B%22distinct_id%22%3A%20%221618f0705b9478-01daa349961edb-32637401-1fa400-1618f0705ba678%22%2C%22%24initial_referrer%22%3A%20%22%24direct%22%2C%22%24initial_referring_domain%22%3A%20%22%24direct%22%7D; _xsrf=2|e1488547|698a7be1f69e283076cfb9258599c80e|1519975023; username-localhost-8888="2|1:0|10:1520412817|23:username-localhost-8888|44:ZGY3ZTIwMmVkZTVlNDk0MmI5Mzk3ODM1YWVkY2E2YjM=|4ddb8cb8f7b23f808d453a3c6f0a490d314efa05ec343de733617f64006d59b5"'}) (2018-03-10 20:03:48; web.py:1591)
Traceback (most recent call last):
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/web.py", line 1512, in _execute
    result = yield result
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
  File "/Users/Mat/anaconda/lib/python3.6/types.py", line 248, in wrapped
    coro = func(*args, **kwargs)
  File "/Users/Mat/github/tornado-app/src/app/models/home/handlers.py", line 11, in get
    self.render( "/Users/Mat/github/tornado-app/src/app/templates/home/home.html")
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/web.py", line 724, in render
    html = self.render_string(template_name, **kwargs)
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/web.py", line 862, in render_string
    t = loader.load(template_name)
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/template.py", line 427, in load
    self.templates[name] = self._create_template(name)
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/template.py", line 454, in _create_template
    with open(path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/Mat/github/tornado-app/src/app/home.html'
ERROR:tornado.access: 500 GET / (::1) 1.28ms (2018-03-10 20:03:48; web.py:2064)
INFO:tornado.access: 200 GET / (::1) 3.79ms (2018-03-10 20:03:56; web.py:2064)
ERROR:tornado.application: Uncaught exception GET / (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/', version='HTTP/1.1', remote_ip='::1', headers={'Host': 'localhost:8888', 'Connection': 'keep-alive', 'Cache-Control': 'max-age=0', 'Upgrade-Insecure-Requests': '1', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'Dnt': '1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept-Language': 'en,es;q=0.9,ca;q=0.8', 'Cookie': 'cookie_ue=1; csrftoken=fIWxIocjADcqNZ1wrwmd5Jda9qvw2iPVdjdsURbbYmSqecZ9HyTsjmHxeVcEp2Jw; mp_26329f50afff012d48b9822b1da66b66_mixpanel=%7B%22distinct_id%22%3A%20%221618f0705b9478-01daa349961edb-32637401-1fa400-1618f0705ba678%22%2C%22%24initial_referrer%22%3A%20%22%24direct%22%2C%22%24initial_referring_domain%22%3A%20%22%24direct%22%7D; _xsrf=2|e1488547|698a7be1f69e283076cfb9258599c80e|1519975023; username-localhost-8888="2|1:0|10:1520412817|23:username-localhost-8888|44:ZGY3ZTIwMmVkZTVlNDk0MmI5Mzk3ODM1YWVkY2E2YjM=|4ddb8cb8f7b23f808d453a3c6f0a490d314efa05ec343de733617f64006d59b5"', 'If-None-Match': '"018d11de8ecd91d4af70218459f79f383cf22d72"'}) (2018-03-10 20:05:21; web.py:1591)
Traceback (most recent call last):
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/web.py", line 1512, in _execute
    result = yield result
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
  File "/Users/Mat/anaconda/lib/python3.6/types.py", line 248, in wrapped
    coro = func(*args, **kwargs)
  File "/Users/Mat/github/tornado-app/src/app/models/home/handlers.py", line 11, in get
    self.render("home.html")
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/web.py", line 724, in render
    html = self.render_string(template_name, **kwargs)
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/web.py", line 862, in render_string
    t = loader.load(template_name)
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/template.py", line 427, in load
    self.templates[name] = self._create_template(name)
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/template.py", line 454, in _create_template
    with open(path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/Mat/github/tornado-app/src/app/models/home/home.html'
ERROR:tornado.access: 500 GET / (::1) 3.72ms (2018-03-10 20:05:21; web.py:2064)
ERROR:tornado.application: Uncaught exception GET / (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/', version='HTTP/1.1', remote_ip='::1', headers={'Host': 'localhost:8888', 'Connection': 'keep-alive', 'Cache-Control': 'max-age=0', 'Upgrade-Insecure-Requests': '1', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'Dnt': '1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept-Language': 'en,es;q=0.9,ca;q=0.8', 'Cookie': 'cookie_ue=1; csrftoken=fIWxIocjADcqNZ1wrwmd5Jda9qvw2iPVdjdsURbbYmSqecZ9HyTsjmHxeVcEp2Jw; mp_26329f50afff012d48b9822b1da66b66_mixpanel=%7B%22distinct_id%22%3A%20%221618f0705b9478-01daa349961edb-32637401-1fa400-1618f0705ba678%22%2C%22%24initial_referrer%22%3A%20%22%24direct%22%2C%22%24initial_referring_domain%22%3A%20%22%24direct%22%7D; _xsrf=2|e1488547|698a7be1f69e283076cfb9258599c80e|1519975023; username-localhost-8888="2|1:0|10:1520412817|23:username-localhost-8888|44:ZGY3ZTIwMmVkZTVlNDk0MmI5Mzk3ODM1YWVkY2E2YjM=|4ddb8cb8f7b23f808d453a3c6f0a490d314efa05ec343de733617f64006d59b5"'}) (2018-03-10 20:06:13; web.py:1591)
Traceback (most recent call last):
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/web.py", line 1512, in _execute
    result = yield result
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
  File "/Users/Mat/anaconda/lib/python3.6/types.py", line 248, in wrapped
    coro = func(*args, **kwargs)
  File "/Users/Mat/github/tornado-app/src/app/models/home/handlers.py", line 11, in get
    self.render("home.html")
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/web.py", line 724, in render
    html = self.render_string(template_name, **kwargs)
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/web.py", line 862, in render_string
    t = loader.load(template_name)
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/template.py", line 427, in load
    self.templates[name] = self._create_template(name)
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/template.py", line 454, in _create_template
    with open(path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/Mat/github/tornado-app/src/app/models/home/home.html'
ERROR:tornado.access: 500 GET / (::1) 3.58ms (2018-03-10 20:06:13; web.py:2064)
ERROR:tornado.application: Uncaught exception GET / (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/', version='HTTP/1.1', remote_ip='::1', headers={'Host': 'localhost:8888', 'Connection': 'keep-alive', 'Cache-Control': 'max-age=0', 'Upgrade-Insecure-Requests': '1', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'Dnt': '1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept-Language': 'en,es;q=0.9,ca;q=0.8', 'Cookie': 'cookie_ue=1; csrftoken=fIWxIocjADcqNZ1wrwmd5Jda9qvw2iPVdjdsURbbYmSqecZ9HyTsjmHxeVcEp2Jw; mp_26329f50afff012d48b9822b1da66b66_mixpanel=%7B%22distinct_id%22%3A%20%221618f0705b9478-01daa349961edb-32637401-1fa400-1618f0705ba678%22%2C%22%24initial_referrer%22%3A%20%22%24direct%22%2C%22%24initial_referring_domain%22%3A%20%22%24direct%22%7D; _xsrf=2|e1488547|698a7be1f69e283076cfb9258599c80e|1519975023; username-localhost-8888="2|1:0|10:1520412817|23:username-localhost-8888|44:ZGY3ZTIwMmVkZTVlNDk0MmI5Mzk3ODM1YWVkY2E2YjM=|4ddb8cb8f7b23f808d453a3c6f0a490d314efa05ec343de733617f64006d59b5"'}) (2018-03-10 20:13:05; web.py:1591)
Traceback (most recent call last):
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/web.py", line 1512, in _execute
    result = yield result
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
  File "/Users/Mat/anaconda/lib/python3.6/types.py", line 248, in wrapped
    coro = func(*args, **kwargs)
  File "/Users/Mat/github/tornado-app/src/app/models/home/handlers.py", line 11, in get
    self.render("home.html")
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/web.py", line 724, in render
    html = self.render_string(template_name, **kwargs)
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/web.py", line 862, in render_string
    t = loader.load(template_name)
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/template.py", line 427, in load
    self.templates[name] = self._create_template(name)
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/template.py", line 454, in _create_template
    with open(path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/Mat/github/tornado-app/src/app/models/home/home.html'
ERROR:tornado.access: 500 GET / (::1) 8.33ms (2018-03-10 20:13:05; web.py:2064)
ERROR:tornado.application: Uncaught exception GET / (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/', version='HTTP/1.1', remote_ip='::1', headers={'Host': 'localhost:8888', 'Connection': 'keep-alive', 'Cache-Control': 'max-age=0', 'Upgrade-Insecure-Requests': '1', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'Dnt': '1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept-Language': 'en,es;q=0.9,ca;q=0.8', 'Cookie': 'cookie_ue=1; csrftoken=fIWxIocjADcqNZ1wrwmd5Jda9qvw2iPVdjdsURbbYmSqecZ9HyTsjmHxeVcEp2Jw; mp_26329f50afff012d48b9822b1da66b66_mixpanel=%7B%22distinct_id%22%3A%20%221618f0705b9478-01daa349961edb-32637401-1fa400-1618f0705ba678%22%2C%22%24initial_referrer%22%3A%20%22%24direct%22%2C%22%24initial_referring_domain%22%3A%20%22%24direct%22%7D; _xsrf=2|e1488547|698a7be1f69e283076cfb9258599c80e|1519975023; username-localhost-8888="2|1:0|10:1520412817|23:username-localhost-8888|44:ZGY3ZTIwMmVkZTVlNDk0MmI5Mzk3ODM1YWVkY2E2YjM=|4ddb8cb8f7b23f808d453a3c6f0a490d314efa05ec343de733617f64006d59b5"'}) (2018-03-10 20:16:48; web.py:1591)
Traceback (most recent call last):
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/web.py", line 1512, in _execute
    result = yield result
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
  File "/Users/Mat/anaconda/lib/python3.6/types.py", line 248, in wrapped
    coro = func(*args, **kwargs)
  File "/Users/Mat/github/tornado-app/src/app/models/home/handlers.py", line 11, in get
    self.render("home.html")
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/web.py", line 724, in render
    html = self.render_string(template_name, **kwargs)
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/web.py", line 862, in render_string
    t = loader.load(template_name)
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/template.py", line 427, in load
    self.templates[name] = self._create_template(name)
  File "/Users/Mat/anaconda/lib/python3.6/site-packages/tornado/template.py", line 454, in _create_template
    with open(path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/Mat/github/tornado-app/src/app/templates/home.html'
ERROR:tornado.access: 500 GET / (::1) 9.28ms (2018-03-10 20:16:48; web.py:2064)
INFO:tornado.access: 200 GET / (::1) 3.93ms (2018-03-10 20:17:35; web.py:2064)
